"""Generate the appendix result tables from the released CSVs into a file the paper \\input s.

Written rather than typed so the tables cannot drift from the data the way a hand-copied number can.
`src/verify_draft.py` checks the numbers quoted in prose; this closes the same gap for the tables.

    python src/make_tables.py     ->  paper/iclr/tables.tex
"""
from __future__ import annotations
import csv, os

FIND = ["Effusion", "Pneumothorax", "Cardiomegaly", "Edema", "Atelectasis",
        "Consolidation", "Infiltration", "Mass", "Nodule"]
ROWS = [("lingshu7b", "Lingshu-7B"), ("internvl3_8b", "InternVL3-8B"), ("qwen7b", "Qwen2.5-VL-7B"),
        ("llavamed7b", "LLaVA-Med-7B"), ("llava15_7b", "LLaVA-1.5-7B")]
METH = [("yesno", "orig."), ("yesno_alt", "rephr."), ("statement", "stmt."), ("negation", "neg.")]
OUT = "paper/iclr/tables.tex"


def cells():
    U = {}
    for r in csv.DictReader(open("runs/utilisation_final.csv")):
        U[(r["arch"], r["concept"])] = r
    L = [r"% generated by src/make_tables.py -- do not edit",
         r"\begin{table}[t]", r"\centering", r"\small", r"\setlength{\tabcolsep}{5pt}",
         r"\caption{\textbf{Every cell behind Figure~\ref{fig:main}.} $F$ is the probe on the untrained "
         r"network of the same architecture, $T$ the probe on the trained model, $B$ the AUROC of the "
         r"model's own answer, and $U=(B-F)/(T-F)$, all at the connector on the same 1000 held-out "
         r"radiographs. Dashes mark the two cells where $T \le F$, for which the ratio is undefined.}",
         r"\label{tab:cells}",
         r"\begin{tabular}{@{}ll@{\hskip 8pt}rrrr@{}}",
         r"\toprule",
         r"Model & Finding & $F$ & $T$ & $B$ & $U$ \\",
         r"\midrule"]
    for k, (a, name) in enumerate(ROWS):
        for i, c in enumerate(FIND):
            r = U.get((a, c))
            if r is None:
                continue
            add = float(r["trained"]) - float(r["floor"])
            us = "---" if add <= 0 else f"${float(r['utilisation']) * 100:+.0f}$\\%"
            L.append(f"{name if i == 0 else ''} & {c} & {float(r['floor']):.3f} & "
                     f"{float(r['trained']):.3f} & {float(r['answer']):.3f} & {us} \\\\")
        L.append(r"\midrule" if k < len(ROWS) - 1 else r"\bottomrule")
    L += [r"\end{tabular}", r"\end{table}", ""]
    return L


def elicit():
    E = list(csv.DictReader(open("runs/elicitation_summary.csv")))
    SHORT = {a: n.replace("-7B", "").replace("-8B", "") for a, n in ROWS}
    L = [r"\begin{table}[t]", r"\centering", r"\small", r"\setlength{\tabcolsep}{5pt}",
         r"\caption{\textbf{Every cell behind Figure~\ref{fig:controls}.} AUROC of the model's answer "
         r"under each of the four readouts, the probe at the connector for comparison, and the fraction "
         r"of the probe-minus-answer gap that the best readout closes.}",
         r"\label{tab:elicit}",
         r"\begin{tabular}{@{}ll" + "rrrr" + "@{\\hskip 8pt}rr@{}}", r"\toprule",
         r"Model & Finding & " + " & ".join(n for _, n in METH) + r" & probe & closed \\", r"\midrule"]
    E.sort(key=lambda r: (r["arch"], r["concept"]))
    prev = None
    for r in E:
        gb, ga = float(r["gap_before"]), float(r["gap_after"])
        frac = "---" if gb <= 0.01 else f"{(gb - ga) / gb * 100:.0f}\\%"
        nm = SHORT.get(r["arch"], r["arch"])
        L.append(f"{nm if r['arch'] != prev else ''} & {r['concept']} & "
                 + " & ".join(f"{float(r[k]):.3f}" for k, _ in METH)
                 + f" & {float(r['probe_connector']):.3f} & {frac} \\\\")
        prev = r["arch"]
    L += [r"\bottomrule", r"\end{tabular}", r"\end{table}", ""]
    return L


def main():
    os.makedirs(os.path.dirname(OUT), exist_ok=True)
    with open(OUT, "w") as fh:
        fh.write("\n".join(cells() + elicit()))
    print(f"wrote {OUT}")


if __name__ == "__main__":
    main()
